### ISSUE TITLE
Like or unlike a post.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/sculpture-drf-api#10]
**EPIC:** Add and like posts.

**As a logged-in user, I would like to like/unlike a post so that I can show my appreciation of the content.**

**Tasks**

- [x] Task 1: Create Like model.
- [x] Task 2: Create LikeList view.
- [x] Task 3: Create LikeDetail view.
