### ISSUE TITLE
User can view all posts they have liked.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/sculpture-drf-api#11]
**EPIC:** Add and like posts.

**As a logged-in user, I would like to view all posts I have liked so that I can scroll through my favourite content.**

**Tasks**

- [x] Task 1: Create Like model.
- [x] Task 2: Create LikeList view.
- [x] Task 3: Create LikeDetail view.
