### ISSUE TITLE
User can view most recent posts first.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/sculpture-drf-api#13]
**EPIC:** View posts.

**As a user, I would like to view the most recent posts first so that I am up to date with the latest content.**

**Tasks**

- [x] Task 1: Create Post model.
- [x] Task 2: Create PostList view.
- [x] Task 3: Create PostDetail view.
