### ISSUE TITLE
View a user's profile.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/sculpture-drf-api#17]
**EPIC:** Profiles.

**As a user, I would like to view other users’ profiles so that I can see their posts and learn more about them.**

**Tasks**

- [x] Task 1: Create Profile model.
- [x] Task 2: Create ProfileList view.
- [x] Task 3: Create ProfileDetail view.
