### ISSUE TITLE
A user can edit their profile.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/sculpture-drf-api#21]
**EPIC:** Profiles.

**As a logged-in user, I would like to edit my profile so that I can keep my details up to date.**

**Tasks**

- [x] Task 1: Create Profile model.
- [x] Task 2: Create ProfileList view.
- [x] Task 3: Create ProfileDetail view.
