### ISSUE TITLE
View user comments.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/sculpture-drf-api#24]
**EPIC:** Comments.

**As a user, I would like to view comments by other users so that I can know what they think about posts.**

**Tasks**

- [x] Task 1: Create Comment model.
- [x] Task 2: Create CommentList view.
- [x] Task 3: Create CommentDetail view.
