### ISSUE TITLE
Comment on a post.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/sculpture-drf-api#26]
**EPIC:** Comments.

**As a logged-in user, I would like to comment on a post so that I can share my thoughts about its content.**

**Tasks**

- [x] Task 1: Create Comment model.
- [x] Task 2: Create CommentList view.
- [x] Task 3: Create CommentDetail view.
