### ISSUE TITLE
Edit a comment.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/sculpture-drf-api#27]
**EPIC:** Comments.

**As a logged-in user, I would like to edit any comment I have made so that I can update its content.**

**Tasks**

- [x] Task 1: Create Comment model.
- [x] Task 2: Create CommentList view.
- [x] Task 3: Create CommentDetail view.
