### ISSUE TITLE
User can book an Online Talk event.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/sculpture-drf-api#33]
**EPIC:** Online talk events.

**As a logged-in user, I would like to submit a booking for an Online Talk event so that I can attend and engage with other users.**

**Tasks**

- [x] Task 1: Create Booking model.
- [x] Task 2: Create BookingList view.
- [x] Task 3: Create BookingDetail view.
