### ISSUE TITLE
User can suggest topics for future Online Talk events.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/sculpture-drf-api#34]
**EPIC:** Online talk events.

**As a logged-in user, I would like to make suggestions for topics at future Online Talk events so that I can learn more about my areas of interest.**

**Tasks**

- [x] Task 1: Create Booking model.
- [x] Task 2: Create BookingList view.
- [x] Task 3: Create BookingDetail view.
