### ISSUE TITLE
Site administration access.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/sculpture-drf-api#35]
**EPIC:** Site administration.

**As an administrator, I would like to access the administrator panel so that I can monitor and delete posts, comments and users if necessary.**

**Tasks**

- [x] Task 1: Install django and import/s from django.contrib.auth.
- [x] Task 2: Create superuser.
- [x] Task 3: Test login as admin.
