### ISSUE TITLE
User can view, edit and delete their Online Talk event bookings.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/sculpture-drf-api#36]
**EPIC:** Online talk events.

**As a logged-in user, I would like to view, edit and delete my bookings for Online Talk events so that I can check and change my bookings if necessary.**

**Tasks**

- [x] Task 1: Create Booking model.
- [x] Task 2: Create BookingList view.
- [x] Task 3: Create BookingDetail view.
