### ISSUE TITLE
Create a post.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/sculpture-drf-api#8]
**EPIC:** Add and like posts.

**As a logged-in user, I would like to create a post to share on the platform so that I can engage with other users.**

**Tasks**

- [x] Task 1: Create Post model.
- [x] Task 2: Create PostList view.
- [x] Task 3: Create PostDetail view.
